### PR TITLE
Proper terrain avoidance and ramming.

### PR DESCRIPTION
**Pull request by BrettRyland**
This is a fix for lawn-darting that supercedes the changes in [Fix clamp override in turning radius calc #3 ](https://github.com/illectro/BDArmory/pull/3).

- Updated `turnRadius` calculation based on slowly decaying pessimistic estimates of the vessel's G-force from dynamic pressure.
- Extra twiddle factor in `MinAltNeeded` that is dynamically adjusted based on recently observed `turnRadius` values.
- Minor amounts of logging.
- Auto-formatting (with vscode) has been applied.

The `turnRadius` calculation is that which I discussed with @TheKurgan, which he indicated seemed to reduce the aggressiveness of the AI slightly (perhaps by breaking off an attack temporarily to avoid hitting the ground). I haven't noticed this personally, but he has more experience, so take it with a grain of salt.
(@TheKurgan I've changed the exit "gain alt" condition to be `minAltitude` and "velocity pointing upwards", which should help resuming an attack more quickly than what I had before.)

From observing the logs, there appears to be a fair amount of variety in the percentage of time spent actually gaining altitude while in "gain alt" mode. The twiddle factor tries to measure and compensate for this.

### CODE REVIEW

**Review by agoodman — APPROVED** [review]

**Comment by TheKurgan** [comment]
I reviewed BrettRyland aka DocNappers patch, it's GOOD 

Ran at least 2 dozen or more battles so far, the results are awesome!

99% reduction in "lawn-dart", and the AI combat is just as good or better then it was before.

**Comment by BrettRyland** [comment]
@TheKurgan I've just tweaked the decay factors to be the same to give more stable turn radius (and hence also the twiddle factor) values. Could you check that that doesn't adversely affect your tests? Thanks!

**Comment by TheKurgan** [comment]
These changes, will they loosen the planes turn radius? The planes turning hard in a yank-and-bank is part of what makes the combat exciting.

**Comment by BrettRyland** [comment]
The latest changes to terrain avoidance.

This is pretty much stable now and I think I'm basically done with the changes required for full terrain avoidance. The only additional item I can think of is a slider for tuning the min and max values of the turn radius twiddle factor for each craft (the twiddle factor is no-longer learned, but varies from min to max depending on the orientation of the craft as it needs to roll to the right angle to pull away from terrain, the min value should also compensate for the reaction time of the plane). Cl0by has said that he can contribute that. The defaults of 2 and 4 should be ok for most planes.

There is a slider in the BDA settings panel to control the frequency of terrain checks for lower spec machines (in case it causes a performance issue). This factor scales by `1+(radarAltitude/500)^2` to reduce it's impact on performance. In my tests, the new code had very little effect on performance.

[Here is a video](https://youtu.be/Q7cQBWC-WXg) of a FFA in the hills north of KSC to demonstrate the terrain avoidance in action.

Note that there are situations where the planes will crash anyway, such as when the terrain becomes increasingly steep such that the initial calculations are insufficient to clear the upcoming terrain. Also, sometimes the vessel is told to head away from the terrain, but it just does barrel rolls until it hits anyway. I'm not sure if/how those can be changed, but hey, RNG happens.

**Comment by BrettRyland** [comment]
Ok, so not quite final. I'm testing some other changes that were requested in another channel. I will update the PR once I'm done with those.

**Comment by BrettRyland** [comment]
OK, the latest changes I was testing have been added (not including the ramming stuff). I believe these have been tested in Project Münway over the last few days and I haven't had any reports of issues or further suggestions.

**Comment by TheKurgan** [comment]
Personally tested these modifications for many many hours... they are very very good!
I hope to be able to incorporate some of this into the official BDAc some time.

**Comment by BrettRyland** [comment]
Ok, more bug fixes and improvements are incoming. I'll give them a few days to be tested in Project Münway before including them here.

**Comment by BrettRyland** [comment]
OK, latest changes (from a few days ago) have been added. This fixes some bugs (also in the avoid other planes code), adds some UI elements and generally makes the terrain avoidance work much better.

**Comment by BrettRyland** [comment]
Improvements to the UI and to the vessel-vessel collision detection. The detection period may need tweaking depending on the manoeuvrability of the plane, but I think it's about right (it's similar to the old period).

**Comment by BrettRyland** [comment]
Ramming code has been added.

This also includes a clean-up of the UI with many settings getting moved to advanced tweakables.

A better check for being out of ammo/guns is included in the ramming code and the check in the competition code has been updated to use this.

**Comment by BrettRyland** [comment]
Added a setting in BDArmory settings to disable ramming on all planes.

**Comment by BrettRyland** [comment]
Added general bugfixes (not just in the new code) and an improvement to the ramming calculations.

**Comment by BrettRyland** [comment]
Ramming logging from Cl0by has been merged.

**Comment by BrettRyland** [comment]
Merged in Cl0by's latest changes for ramming logging.

Added a toggle in the BDArmory Settings for an alternative target selection for FFA-style combats. Instead of selecting the least engaged enemy target, it selects the closest enemy target with a bias towards those in front of it and a 10% hysteresis for the current target. This should prevent excessive target hopping.

**Comment by BrettRyland** [comment]
The rewrite of the ramming logging is now merged with this pull request.
Also a couple of general bugs have been squashed.
And a convenience function or two for Scott have been added.

**Comment by BrettRyland** [comment]
Individual axis dynamic steer damping has been added.

**Comment by BrettRyland** [comment]
Added a threat level and an evasion threshold slider for determining when to go into evasion.

**Comment by BrettRyland** [comment]
Added in all the latest changes from the "BDArmory for Runway Project" v1.1.1 on CKAN.

The only thing that isn't merged yet is @agoodman's remote orchestration as it appears to need some more work.

I think this is suitable for you (@illectro) to merge into your branch and make your secret modifications now in preparation for season 2.

**Comment by BrettRyland** [comment]
We decided to get missiles working properly with a scoring system based on damaged parts (not necessarily destroyed though, i.e., like bullet hits). Spawning is much improved. Also, the camera switching for incoming missiles has been improved.

**Pull request merged**
